import SwiftUI
import AppKit
import Combine
import DrawerEngine
import LogKit
import UniformTypeIdentifiers

/// A file dropped onto the shelf.
public struct ShelfFile: Identifiable, Sendable {
    public let id: UUID
    public var name: String
    public var url: URL?
    public var systemImage: String
    public init(id: UUID = UUID(), name: String, url: URL? = nil, systemImage: String) {
        self.id = id; self.name = name; self.url = url; self.systemImage = systemImage
    }
}

/// Which pane of the drawer is showing.
public enum TrayPane: String, CaseIterable, Sendable {
    case clipboard, shelf, notes
    public var title: String {
        switch self {
        case .clipboard: return "Clipboard"
        case .shelf:     return "Shelf"
        case .notes:     return "Notes"
        }
    }
    public var systemImage: String {
        switch self {
        case .clipboard: return "doc.on.clipboard"
        case .shelf:     return "tray.full"
        case .notes:     return "note.text"
        }
    }
}

@MainActor
public final class TrayViewModel: ObservableObject {
    @Published public var pane: TrayPane = .clipboard
    @Published public var query: String = ""
    @Published public var files: [ShelfFile] = []
    @Published public var note: String = ""

    /// Auto-capture watches the system clipboard and files new copies
    /// automatically. Persisted across launches.
    @Published public var autoCapture: Bool {
        didSet {
            UserDefaults.standard.set(autoCapture, forKey: Keys.autoCapture)
            if autoCapture { startMonitoring() } else { stopMonitoring() }
            AppLog.info("auto-capture \(autoCapture ? "on" : "off")", category: "clipboard")
        }
    }

    /// True when a private-mode passcode is set.
    @Published public private(set) var hasPasscode: Bool
    /// True when private mode is engaged and the user hasn't entered the passcode
    /// this session — clip contents are masked.
    @Published public private(set) var isLocked: Bool = false

    public let clips: ClipboardStore

    private let passcode: PasscodeStore
    private let service = "com.plainware.tray"
    private var bag = Set<AnyCancellable>()
    private var pollTimer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private enum Keys {
        static let autoCapture = "tray.autoCapture"
    }

    /// Pasteboard types that signal sensitive / transient content set by
    /// password managers and the like. The three `org.nspasteboard.*` universal
    /// types (nspasteboard.org convention) plus a default legacy ignore list.
    /// We never auto-capture an item carrying any of these.
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
        .init("net.antelle.keeweb"),
        .init("com.apple.is-remote-clipboard"),
    ]

    public init() {
        let store = EncryptedClipPersistence(service: service)
        self.clips = ClipboardStore(persistence: store)
        self.passcode = PasscodeStore(service: service)
        self.hasPasscode = passcode.isSet
        self.isLocked = passcode.isSet           // start locked if a passcode exists
        self.autoCapture = UserDefaults.standard.object(forKey: Keys.autoCapture) as? Bool ?? true

        // Re-publish the store's changes so views observing the view model
        // refresh immediately when clips are added / removed / pinned.
        clips.objectWillChange
            .sink { [weak self] _ in self?.objectWillChange.send() }
            .store(in: &bag)

        if autoCapture { startMonitoring() }
    }

    // MARK: Clipboard monitoring

    /// Items currently shown in the clipboard pane (filtered by `query`).
    public var visibleClips: [ClipItem] {
        clips.search(query)
    }

    private func startMonitoring() {
        guard pollTimer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.pollClipboard() }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
        AppLog.info("clipboard monitor started", category: "clipboard")
    }

    private func stopMonitoring() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    private func pollClipboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        // Respect concealed / transient markers from password managers.
        if let types = pb.types, !Self.concealedTypes.isDisjoint(with: Set(types)) {
            AppLog.info("skipped concealed clipboard item", category: "clipboard")
            return
        }
        if let s = pb.string(forType: .string) { add(s) }
    }

    /// Manually capture the current text contents of the general pasteboard.
    public func captureClipboard() {
        lastChangeCount = NSPasteboard.general.changeCount
        if let s = NSPasteboard.general.string(forType: .string) {
            add(s)
        } else {
            AppLog.warn("clipboard capture found no text", category: "clipboard")
        }
    }

    public func add(_ text: String) {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        clips.add(text)
        AppLog.info("clipboard item captured (kind=\(classify(text).rawValue))", category: "clipboard")
    }

    public func togglePin(_ id: UUID) { clips.togglePin(id) }
    public func remove(_ id: UUID) { clips.remove(id) }
    public func clearUnpinned() { clips.clearUnpinned() }

    /// Copy a clip's text back onto the pasteboard. The user presses Cmd-V
    /// themselves — we deliberately do NOT synthesize a paste keystroke.
    public func copyToPasteboard(_ item: ClipItem) {
        guard !isLocked else { return }   // don't leak masked content while locked
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(item.text, forType: .string)
        lastChangeCount = NSPasteboard.general.changeCount   // don't re-capture our own write
    }

    // MARK: Private mode

    /// What to render for an item, honouring the lock state. When locked, only
    /// the first couple of characters of the first line are shown; the rest is
    /// masked with bullets.
    public func displayText(for item: ClipItem) -> String {
        guard isLocked else { return item.text }
        let firstLine = item.text.split(whereSeparator: \.isNewline).first.map(String.init) ?? item.text
        let visible = String(firstLine.prefix(2))
        let dots = max(4, min(10, firstLine.count - 2))
        return visible + String(repeating: "•", count: dots)
    }

    public func setPasscode(_ code: String) {
        let trimmed = code.trimmingCharacters(in: .whitespaces)
        guard trimmed.count >= 4 else { return }
        passcode.set(trimmed)
        hasPasscode = true
        isLocked = false        // setting it implicitly unlocks the current session
        AppLog.info("private-mode passcode set", category: "privacy")
    }

    /// Returns false on a wrong passcode.
    @discardableResult
    public func unlock(_ code: String) -> Bool {
        guard passcode.verify(code.trimmingCharacters(in: .whitespaces)) else {
            AppLog.warn("private-mode unlock failed", category: "privacy")
            return false
        }
        isLocked = false
        AppLog.info("private mode unlocked", category: "privacy")
        return true
    }

    public func lock() {
        guard hasPasscode else { return }
        isLocked = true
        AppLog.info("private mode locked", category: "privacy")
    }

    /// Remove the passcode (requires the current one).
    @discardableResult
    public func removePasscode(_ current: String) -> Bool {
        guard passcode.verify(current.trimmingCharacters(in: .whitespaces)) else { return false }
        passcode.clear()
        hasPasscode = false
        isLocked = false
        AppLog.info("private-mode passcode removed", category: "privacy")
        return true
    }

    // MARK: Shelf

    @discardableResult
    public func loadDrop(_ providers: [NSItemProvider]) -> Bool {
        var handled = false
        for provider in providers where provider.hasItemConformingToTypeIdentifier(UTType.fileURL.identifier) {
            handled = true
            _ = provider.loadObject(ofClass: URL.self) { [weak self] url, _ in
                guard let url else { return }
                Task { @MainActor in self?.addFile(url) }
            }
        }
        return handled
    }

    public func addFile(_ url: URL) {
        files.insert(ShelfFile(name: url.lastPathComponent, url: url, systemImage: Self.icon(for: url)), at: 0)
        AppLog.info("file added to shelf: \(url.lastPathComponent)", category: "shelf")
    }

    public func removeFile(_ id: UUID) {
        files.removeAll { $0.id == id }
    }

    static func icon(for url: URL) -> String {
        switch url.pathExtension.lowercased() {
        case "png", "jpg", "jpeg", "gif", "heic", "tiff": return "photo"
        case "pdf":                                        return "doc.richtext"
        case "zip", "tar", "gz":                           return "doc.zipper"
        case "mov", "mp4", "m4v":                          return "film"
        case "mp3", "wav", "aac", "m4a":                   return "music.note"
        case "txt", "md", "rtf":                           return "doc.text"
        case "":                                           return "folder"
        default:                                           return "doc"
        }
    }

    /// The live inline-calc result for the last non-empty note line, if any.
    public var noteResult: String? {
        guard let line = note
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map(String.init)
            .last(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty })
        else { return nil }
        return evaluateInline(line)
    }

    /// Last inline-calc result we logged, to avoid logging on every keystroke.
    private var lastLoggedNoteResult: String?

    /// Recompute the inline-calc result and log it once when it changes.
    /// Call from the notes view's `onChange(of:)`.
    public func noteChanged() {
        let result = noteResult
        guard result != lastLoggedNoteResult else { return }
        lastLoggedNoteResult = result
        if let result {
            AppLog.info("note inline-calc evaluated → \(result)", category: "notes")
        }
    }
}
